updated yml file v9

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,7 +18,7 @@ jobs:
         uses: actions/setup-java@v2
         with:
           java-version: '17'
-          distribution: 'temurin'  # Specify the distribution to use (e.g., temurin, zulu, adopt)
+          distribution: 'temurin'  # Specify the distribution to use
 
       - name: Install Google Chrome
         run: |
@@ -33,13 +33,20 @@ jobs:
         run: |
           CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
           echo "CHROME_VERSION=${CHROME_VERSION}" >> $GITHUB_ENV
-          MAJOR_CHROME_VERSION=$(echo ${CHROME_VERSION} | cut -d '.' -f 1-2)
+          MAJOR_CHROME_VERSION=$(echo ${CHROME_VERSION} | cut -d '.' -f 1)
           echo "MAJOR_CHROME_VERSION=${MAJOR_CHROME_VERSION}" >> $GITHUB_ENV
 
       - name: Download ChromeDriver
         run: |
           echo "Requesting ChromeDriver for Chrome version ${MAJOR_CHROME_VERSION}"
           CHROME_DRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${MAJOR_CHROME_VERSION}" | tr -d '\n')
+          
+          # Check if ChromeDriver version retrieval was successful
+          if [[ "${CHROME_DRIVER_VERSION}" == "" ]]; then
+            echo "Failed to retrieve ChromeDriver version for major version ${MAJOR_CHROME_VERSION}"
+            exit 1
+          fi
+
           echo "CHROME_DRIVER_VERSION=${CHROME_DRIVER_VERSION}" >> $GITHUB_ENV
           echo "Downloading ChromeDriver version ${CHROME_DRIVER_VERSION}"
           wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
